source/includes/_customers.md
=> Add UnsupportedBank error to dwolla.js IAV docs

source/includes/_customers.md
=> Add RateLimitReached to IAV error codes

source/includes/_fundingsrcs.md
To match https://github.com/Dwolla/dwolla-swagger-php/blob/3469d4b7464c50da86348f732a27e6f1d72ce7bf/lib/FundingsourcesApi.php#L662
=> Update PHP Micro Deposit calls

source/layouts/layout.erb
=> Mimic .com

source/includes/_accounts.md, source/includes/_customers.md, source/includes/_documents.md, source/includes/_events.md, source/includes/_fundingsrcs.md, source/includes/_introduction.md, source/includes/_masspay.md, source/includes/_oauth.md, source/includes/_root.md, source/includes/_transfers.md, source/includes/_webhookSubscriptions.md, source/includes/_webhooks.md, source/includes/transfer/_accounts.md, source/includes/transfer/_events.md, source/includes/transfer/_fundingsrcs.md, source/includes/transfer/_introduction.md, source/includes/transfer/_masspay.md, source/includes/transfer/_oauth.md, source/includes/transfer/_root.md, source/includes/transfer/_transfers.md, source/includes/transfer/_webhookSubscriptions.md, source/includes/transfer/_webhooks.md
remove code examples for no longer supported swagger generated sdks.
=> Cleanup code samples

source/includes/_fundingsrcs.md, source/includes/transfer/_oauth.md
Adding support for returning iavAccountHolders
=> FundingSource object now has an optional iavAccountHolders parameter

source/layouts/layout.erb, source/layouts/transfer.erb
Add link to integrations page in footer
=> Add integrations link to footer

source/includes/_accounts.md, source/includes/_customers.md, source/includes/_masspay.md, source/includes/_transfers.md, source/includes/transfer/_masspay.md, source/includes/transfer/_transfers.md
Add support for correlationId on MassPay and MassPay items
=> add support for correlationId

source/includes/_customers.md, source/includes/_fundingsrcs.md
Can you look at this and give feedback?
=> Fingerprint plus

source/includes/_accounts.md, source/includes/_customers.md, source/includes/_transfers.md, source/includes/transfer/_masspay.md
Added correlationId to MassPay parameter for listing customer // account. Added code example.  Removed $ dollar sign from total and totalFees. Uppercased
USD
=> More Misc Fixes

source/includes/_accounts.md, source/includes/_customers.md, source/includes/_fundingsrcs.md, source/includes/_transfers.md, source/includes/transfer/_fundingsrcs.md
bankAccountType additions, one-off fixes.
=> bankAccountType+Misc

source/layouts/layout.erb, source/layouts/transfer.erb
Moved IndustryInitiatives to the bottom of the footer
=> Moved IndustryInitiatives to the bottom of the footer

source/includes/_events.md, source/includes/_webhookSubscriptions.md
Hopefully the wording makes sense. If not, feel free to let me know
=> Added two new events, added ten webhook subscription limit

source/includes/_events.md, source/includes/_masspay.md
Not sure if this needs legal approval??
=> Mass pay item failure code and reason

README.md
=> Platform Focus

source/includes/transfer/_introduction.md, source/layouts/transfer.erb
TRANSFER v2DOCS 
Killing the dropdown thing on top.
Replacing the Transfer Link
Oh hi mark
=> kill dropdown and links

source/includes/_customers.md
- add support for update businessName on receive-only Customer
- remove receive-only as possible Customer status filter
=> add support for update business name

source/includes/_events.md, source/includes/_introduction.md
Add BO Webhooks
Add TLS 1.2 update alert. TLS 1.0 // 1.1 deprecation warning.
=> Add beneficial Owner and TLS update alert

source/includes/_beneficialOwners.md, source/includes/_customers.md, source/includes/_events.md, source/includes/_introduction.md, source/index.md
Beneficial Owners 
New events
Cleanup on TLS wording.
=> beneficial owners endpoints, events, cleanup

source/includes/_beneficialOwners.md, source/includes/_customers.md
Cleanup of some beneficial owners stuff
Formatting.
=> BO Cleanup

source/includes/_beneficialOwners.md, source/includes/_customers.md, source/includes/_documents.md, source/includes/_webhookSubscriptions.md
Change webhook subscription retry time
Remove tif as supported file extension for document upload
Restructure Business Verified Customer section
=> More Misc Edits

source/includes/_events.md
- Added funding_source_updated and customer_funding_source_updated webhook and description
=> Webhook addition

source/includes/_customers.md, source/includes/_events.md, source/includes/_introduction.md, source/includes/_masspay.md
- Added soleProp biz parameter section 
- Added MassPayment needing more than one item
=> SoleProp Addition

source/includes/_transfers.md
add support for addenda information within achDetails object on created bank transfers
=> add support for addenda information

source/includes/_documents.md
HTTP Status for document creation.
=> Document status

source/layouts/layout.erb, source/stylesheets/lib/style-tiles/sass/developer/partials/_disclaimer.scss, source/stylesheets/lib/style-tiles/sass/developer/partials/_header.scss, source/stylesheets/lib/style-tiles/sass/developer/partials/_side-nav.scss, source/stylesheets/lib/style-tiles/sass/developer/partials/_typography.scss, source/stylesheets/overrides/_toc.scss
Font size and color
Footer
Toc padding on top
=> marComm Cleanup

source/includes/_masspay.md, source/includes/_transfers.md
Addenda addition on masspayments
Transfer cleanup
Cancel transfer cleanup
=> Addenda MassPay

source/includes/_accounts.md, source/includes/_beneficialOwners.md, source/includes/_customers.md, source/includes/_documents.md, source/includes/_events.md, source/includes/_fundingsrcs.md, source/includes/_masspay.md, source/includes/_oauth.md, source/includes/_root.md, source/includes/_sdks.md, source/includes/_transfers.md, source/includes/_webhookSubscriptions.md, source/includes/_webhooks.md
Fixed minor errors, and inconsistencies in the SDKs for the following:
Introduction
SDK Support
Authorization
Root
Accounts
Customers
Beneficial Owners
Documents
=> fixed variable-name inconsistencies in all SDKs

source/includes/_transfers.md
Clarify addenda, correlationId
=> Transfer Parameters

README.md, source/includes/_accounts.md, source/includes/_events.md, source/includes/_oauth.md, source/includes/_sdks.md
- Changed links: `www.dwolla.com/applications` to `dashboard.dwolla.com/applications`
- Changed links: `https://dashboard-sandbox.dwolla.com/applications` to `https://dashboard-sandbox.dwolla.com/applications-legacy`
- Updated Master Account's Transfer events' descriptions.
=> Updated transfer events description

source/includes/_webhookSubscriptions.md
- Webhooks limit text
- Added Error Code for "Max number of webhook subscriptions created"
=> Updated text about Webhooks Subscriptions limit

source/includes/_customers.md, source/includes/_documents.md, source/includes/_transfers.md, source/layouts/layout.erb
- Fixed issues #157 and #160. 
- Marked business name as `optional` for Receive-only Customers (DR-199)
- Updated `Contact Sales` links to `Get Started` (DR-198)
- Fixed Dashboard links (DR-197)
- Removed broken link (DR - 203)
- Updated language on onboarding users as Customers (DR 218)
=> Fixed issues 

source/includes/_customers.md, source/includes/_fundingsrcs.md
Added notes on retry
Added guidance on removing funding source while transfer is in flight
=> Customers and Funding Sources cleanup

source/includes/_customers.md, source/includes/_webhookSubscriptions.md
- Added new Webhooks Delivery rate sections
- Added more detail on pagination to `List Customers` section
=> Added new sections to Webhooks, and List Customers

source/includes/_sdks.md, source/javascripts/dwolla/groupCodeSnippets.js
DR-262 - Added Kotlin SDK as a new preview to the `SDK Support` section
=> Added support for Kotlin SDK

source/includes/_events.md
Updated webhook topics for KBA related events.
=> Updated KBA verification webhook topics

source/layouts/layout.erb
Add cookie consent to merge on 1/1
=> add cookie consent to api docs

source/includes/_fundingsrcs.md, source/includes/_transfers.md
DEV-272: Add Microdeposits error response
DEV-271/280: Fee response update + added 429 error
DEV-447: On-demand auth funding-source example
=> Minor edits

source/includes/_beneficialOwners.md
=> Added UBO error and status codes

source/includes/_transfers.md
Updated to match this table - https://developers.dwolla.com/resources/bank-transfer-workflow/transfer-failures.html#list-of-possible-return-codes-descriptions-and-actions
=> Update Transfer section  about return codes

source/includes/_customers.md, source/includes/_kba.md
- Added kba and deactivated as possible Customer statuses to the Customer Resource table
- Added an alert box to the KBA section
=> Added kba and deactivated as possible Customer statuses
